/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as ApiMessagesRouteImport } from './routes/api/messages'
import { Route as ApiSourcesRouteImport } from './routes/api/sources'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiTelegramRouteImport } from './routes/api/telegram'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesRoute = ApiMessagesRouteImport.update({
  id: '/api/messages',
  path: '/api/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSourcesRoute = ApiSourcesRouteImport.update({
  id: '/api/sources',
  path: '/api/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramRoute = ApiTelegramRouteImport.update({
  id: '/api/telegram',
  path: '/api/telegram',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/sources': typeof ApiSourcesRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/telegram': typeof ApiTelegramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/sources': typeof ApiSourcesRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/telegram': typeof ApiTelegramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/sources': typeof ApiSourcesRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/telegram': typeof ApiTelegramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed'
    | '/search'
    | '/settings'
    | '/sources'
    | '/api/messages'
    | '/api/sources'
    | '/api/stats'
    | '/api/stream'
    | '/api/telegram'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed'
    | '/search'
    | '/settings'
    | '/sources'
    | '/api/messages'
    | '/api/sources'
    | '/api/stats'
    | '/api/stream'
    | '/api/telegram'
  id:
    | '__root__'
    | '/'
    | '/feed'
    | '/search'
    | '/settings'
    | '/sources'
    | '/api/messages'
    | '/api/sources'
    | '/api/stats'
    | '/api/stream'
    | '/api/telegram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedRoute: typeof FeedRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  ApiMessagesRoute: typeof ApiMessagesRoute
  ApiSourcesRoute: typeof ApiSourcesRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiTelegramRoute: typeof ApiTelegramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages': {
      id: '/api/messages'
      path: '/api/messages'
      fullPath: '/api/messages'
      preLoaderRoute: typeof ApiMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sources': {
      id: '/api/sources'
      path: '/api/sources'
      fullPath: '/api/sources'
      preLoaderRoute: typeof ApiSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram': {
      id: '/api/telegram'
      path: '/api/telegram'
      fullPath: '/api/telegram'
      preLoaderRoute: typeof ApiTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedRoute: FeedRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  ApiMessagesRoute: ApiMessagesRoute,
  ApiSourcesRoute: ApiSourcesRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiTelegramRoute: ApiTelegramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
